Vagrant.configure("2") do |config|
  config.vm.box = "dietpi"
  config.vm.box_check_update = true

  config.vm.provider "virtualbox" do |vb|
    vb.name = "DietPi"
    vb.gui = false
    vb.memory = 2048
  end
  
  config.vm.provision "shell", path: "install_zabbix-agent2.sh"
  config.vm.provision "shell", path: "config_zabbix-agent2.sh"
end
